from pathlib import Path

path = Path('src/LagoVista.UserAdmin/Managers/AppUserTestingManager.cs')
text = path.read_text(encoding='utf-8-sig')


def once(old, new, label):
    global text
    count = text.count(old)
    if count != 1:
        raise SystemExit(f'{label}: expected once, found {count}')
    text = text.replace(old, new, 1)

once('''        public async Task<InvokeResult> AddTestScenarioAsync(AppUserTestScenario testScenario, EntityHeader org, EntityHeader user)\n        {\n            ValidationCheck(testScenario, Actions.Create);\n            await AuthorizeAsync(user, org, typeof(AppUserTestScenario), Actions.Create);\n            await _testScenarioRepo.AddDSLAsync(testScenario);\n            return InvokeResult.Success;\n        }\n\n        public async Task<InvokeResult> UpdateTestScenarioAsync(AppUserTestScenario testScenario, EntityHeader org, EntityHeader user)\n        {\n            ValidationCheck(testScenario, Actions.Update);\n            await AuthorizeAsync(user, org, typeof(AppUserTestScenario), Actions.Update);\n            await _testScenarioRepo.UpdateTestScenarioAsync(testScenario);\n            return InvokeResult.Success;\n        }\n\n        public async Task<AppUserTestScenario> GetTestScenarioAsync(string id, EntityHeader org, EntityHeader user)\n        {\n            var scenario = await _testScenarioRepo.GetByIdAsync(id);\n            await AuthorizeAsync(scenario, AuthorizeResult.AuthorizeActions.Read, user, org);\n            return scenario;\n        }''', '''        public Task<InvokeResult> AddTestScenarioAsync(AppUserTestScenario testScenario, EntityHeader org, EntityHeader user)\n        {\n            return Task.FromResult(InvokeResult.FromError("ReadOnlyScenarioDefinition", "Authentication scenarios are authored in canonical auth-model JSON and are read-only at runtime."));\n        }\n\n        public Task<InvokeResult> UpdateTestScenarioAsync(AppUserTestScenario testScenario, EntityHeader org, EntityHeader user)\n        {\n            return Task.FromResult(InvokeResult.FromError("ReadOnlyScenarioDefinition", "Authentication scenarios are authored in canonical auth-model JSON and are read-only at runtime."));\n        }\n\n        public async Task<AppUserTestScenario> GetTestScenarioAsync(string id, EntityHeader org, EntityHeader user)\n        {\n            await AuthorizeOrgAccessAsync(user, org, typeof(AppUserTestScenario), Actions.Read);\n            return await _testScenarioRepo.GetByIdAsync(id);\n        }''', 'scenario create update get')

once('''        public async Task<InvokeResult> DeleteTestScenarioAsync(string id, EntityHeader org, EntityHeader user)\n        {\n            var scenario = await _testScenarioRepo.GetByIdAsync(id);\n            await AuthorizeAsync(scenario, AuthorizeResult.AuthorizeActions.Delete, user, org);\n            await _testScenarioRepo.DeleteByIdAsync(id);\n            return InvokeResult.Success;\n        }''', '''        public Task<InvokeResult> DeleteTestScenarioAsync(string id, EntityHeader org, EntityHeader user)\n        {\n            return Task.FromResult(InvokeResult.FromError("ReadOnlyScenarioDefinition", "Authentication scenarios are authored in canonical auth-model JSON and are read-only at runtime."));\n        }''', 'scenario delete')

once('''            var scenario = await _testScenarioRepo.GetByIdAsync(run.TestScenario.Id);\n            await VerifyCompletedRunAsync(run, scenario, org, user);\n            await _testRunStore.CreateRunAsync(run);\n\n            var platformStatus = GetPlatformStatus(scenario, run.Platform);\n\n            platformStatus.Status = run.Status;\n            platformStatus.LastRun = run.Finished;\n            platformStatus.LastRunId = run.Id;\n            platformStatus.FinalViewId = run.FinalViewId;\n            platformStatus.ErrorMessage = run.ErrorMessage;\n\n            scenario.LastUpdatedDate = now;\n            scenario.LastUpdatedBy = user;\n            await _testScenarioRepo.UpdateTestScenarioAsync(scenario);\n            return InvokeResult.Success;''', '''            var scenario = await _testScenarioRepo.GetByIdAsync(run.TestScenario.Id);\n            await VerifyCompletedRunAsync(run, scenario, org, user);\n            await _testRunStore.CreateRunAsync(run);\n            return InvokeResult.Success;''', 'run scenario mutation')

path.write_text(text, encoding='utf-8')
