using LagoVista.Core.Attributes;
using LagoVista.UserAdmin.Models.Resources;
using System;
using System.Collections.Generic;
using System.Text;

namespace LagoVista.UserAdmin.Models.Auth
{
    [EntityDescription(
        Domains.AuthDomain,
        UserAdminResources.Names.MobileOAuthPendingAuth_Name,
        UserAdminResources.Names.MobileOAuthPendingAuth_Help,
        UserAdminResources.Names.MobileOAuthPendingAuth_Description,
        EntityDescriptionAttribute.EntityTypes.OrganizationModel,
        typeof(UserAdminResources))]
    public sealed class MobileOAuthPendingAuth
    {
        /// <summary>
        /// One-time code returned to the mobile app via deep link.
        /// Used as the cache key or part of it.
        /// </summary>
        public string Code { get; set; } = default!;

        /// <summary>
        /// Original state value generated by the app.
        /// Used to correlate setiation with callback.
        /// </summary>
        public string State { get; set; } = default!;

        /// <summary>
        /// PKCE-style challenge: BASE64URL(SHA256(verifier)).
        /// The verifier itself never leaves the device.
        /// </summary>
        public string Challenge { get; set; } = default!;

        /// <summary>
        /// Optional: where the app should navigate after login completes.
        /// </summary>
        public string ReturnPath { get; set; }

        /// <summary>
        /// Optional: bind redemption to a specific app installation.
        /// </summary>
        public string AppInstanceId { get; set; }

        /// <summary>
        /// Optional: bind redemption to a device.
        /// </summary>
        public string DeviceId { get; set; }

        /// <summary>
        /// When this record was created.
        /// </summary>
        public string CreationDate { get; set; }

        /// <summary>
        /// Absolute expiration time (usually CreatedAt + 1–2 minutes).
        /// Cache TTL should align with this.
        /// </summary>
        public string ExpiratoinTimeStamp { get; set; }

        /// <summary>
        /// Prevents replay.
        /// </summary>
        public bool Redeemed { get; set; }
    }
}
